# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/00_coretest.ipynb.

# %% auto 0
__all__ = ['addition', 'say_hello']

# %% ../nbs/00_coretest.ipynb 3
''' Skrrt '''
def addition(a,b): return a+b

# %% ../nbs/00_coretest.ipynb 4
def say_hello(to):
    "Say hello to somebody"
    return f'Hello {to}!'
